// TypesFromSerializers CacheKey 0a3cb139139906d63f7b4a526eaf4798
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Todo {
  id: number
  name?: string
  created_at: string | Date
  updated_at: string | Date
}
