// TypesFromSerializers CacheKey ad936762ba98ae4db8f8fa292d49c764
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TodoProps {
  id: number
  name?: string
  created_at: string
  updated_at: string
}
